name: Lint Python Code

on: [push]

jobs:
  lint_python_code:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Show current directory content
      run: |
        ls -la
    - name: Install dev requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Analyzing the code with linter
      run: |
        flake8 .
